#pragma once

//TODO: Get all the assets automatically from a directory 

enum ggfxAssets
{
    checker_1,
    checker_2,
    basic_vert,
    basic_frag,
    teapot,
    cube,
    dragon,
    sponza,
    cube_bob,
    teapot_bob,
    monkey_bob,
    suzanne_bob,
    dragon_bob,
    vivi_bob,
    cube_bof,
    teapot_bof,
    fox_bof,
    sphere_bof,
    sphere_bob,
    sphere2_bof,
    cube_uv_bof,
    cubemap_posx,
    cubemap_negx,
    cubemap_posy,
    cubemap_negy,
    cubemap_negz,
    cubemap_posz,
    cubemap_vert_shader,
    cubemap_frag_shader,
    torus_bof,
    torus_bob,
    cube_uv_bob,
    icosphere_bof,
};

static const char* assetPaths[] =
{
    "examples/00 Hello Triangle/assets/checker.png",
    "examples/00 Hello Triangle/assets/checker2.png",
    "examples/00 Hello Triangle/assets/basic.vert",
    "examples/00 Hello Triangle/assets/basic.frag",
    "examples/00 Hello Triangle/assets/teapot.obj",
    "examples/00 Hello Triangle/assets/cube.obj",
    "examples/00 Hello Triangle/assets/dragon.obj",
    "examples/00 Hello Triangle/assets/sponza.obj",
    "examples/00 Hello Triangle/assets/cube.bob",
    "examples/00 Hello Triangle/assets/teapot.bob",
    "examples/00 Hello Triangle/assets/monkey.bob",
    "examples/00 Hello Triangle/assets/suzanne.bob",
    "examples/00 Hello Triangle/assets/dragon.bob",
    "examples/00 Hello Triangle/assets/vivi.bob",
    "examples/00 Hello Triangle/assets/cube.bof",
    "examples/00 Hello Triangle/assets/teapot.bof",
    "examples/00 Hello Triangle/assets/fox.bof",
    "examples/00 Hello Triangle/assets/sphere.bof",
    "examples/00 Hello Triangle/assets/sphere.bob",
    "examples/00 Hello Triangle/assets/sphere2.bof",
    "examples/00 Hello Triangle/assets/cube_uv.bof",
    "examples/00 Hello Triangle/assets/sky/sky_right.bmp",
    "examples/00 Hello Triangle/assets/sky/sky_left.bmp",
    "examples/00 Hello Triangle/assets/sky/sky_top.bmp",
    "examples/00 Hello Triangle/assets/sky/sky_bottom.bmp",
    "examples/00 Hello Triangle/assets/sky/sky_back.bmp",
    "examples/00 Hello Triangle/assets/sky/sky_front.bmp",
    "examples/00 Hello Triangle/assets/cubemap.vert",
    "examples/00 Hello Triangle/assets/cubemap.frag",
    "examples/00 Hello Triangle/assets/torus.bof",
    "examples/00 Hello Triangle/assets/torus.bob",
    "examples/00 Hello Triangle/assets/cube_uv.bob",
    "examples/00 Hello Triangle/assets/icosphere.bof",
};